# Generated by Django 4.0 on 2022-01-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default1.png', null=True, upload_to=''),
        ),
    ]
