# Generated by Django 4.0.1 on 2022-01-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_office_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='booking',
        ),
    ]
