# Generated by Django 4.0 on 2022-01-13 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.IntegerField(null=True)),
                ('applicant_name', models.CharField(max_length=200, null=True)),
                ('IC_no', models.IntegerField(null=True)),
                ('student_tel_no', models.IntegerField(null=True)),
                ('supervisor', models.CharField(max_length=200, null=True)),
                ('staff_no', models.IntegerField(null=True)),
                ('programme', models.CharField(max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default1.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('feedback', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_code', models.CharField(max_length=50, null=True)),
                ('number_of_users', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('HI_work_activity', models.CharField(max_length=100, null=True)),
                ('HI_hazard', models.CharField(max_length=100, null=True)),
                ('HI_source', models.CharField(max_length=100, null=True)),
                ('RA_existing_risk_control', models.CharField(max_length=100, null=True)),
                ('RA_likelihood', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('RA_severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('RA_risk', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)])),
                ('RC_countermeasure', models.CharField(max_length=100, null=True)),
                ('RC_PIC', models.CharField(max_length=100, null=True)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('remarks', models.CharField(default='-', max_length=200)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.applicant')),
            ],
        ),
    ]
