# Generated by Django 4.0 on 2022-01-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, null=True)),
                ('staff_no', models.IntegerField(null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('tel_no', models.IntegerField(null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='functions.booking')),
            ],
        ),
    ]
