# Generated by Django 4.0 on 2022-01-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
