# Generated by Django 4.0.1 on 2022-01-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_delete_office'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ApplicantFeedback',
        ),
    ]
