# Generated by Django 4.0.1 on 2022-01-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0004_rename_feedback_applicantfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='profile_pic',
        ),
    ]
